import { AdminAnalyticData, LeaderboardData } from "@/types";

export const MOCK_LEADERBOARD_DATA: LeaderboardData = {
  users: [
    {
      id: "user-20",
      name: "Pengguna 20",
      role: "USER",
      points: 976,
      rank: 1,
    },
    {
      id: "user-2",
      name: "Pengguna 2",
      role: "USER",
      points: 880,
      rank: 2,
    },
    {
      id: "user-7",
      name: "Pengguna 7",
      role: "USER",
      points: 733,
      rank: 3,
    },
    {
      id: "user-18",
      name: "Pengguna 18",
      role: "USER",
      points: 714,
      rank: 4,
    },
    {
      id: "user-13",
      name: "Pengguna 13",
      role: "USER",
      points: 667,
      rank: 5,
    },
    {
      id: "user-9",
      name: "Pengguna 9",
      role: "USER",
      points: 647,
      rank: 6,
    },
    {
      id: "user-1",
      name: "Pengguna 1",
      role: "USER",
      points: 576,
      rank: 7,
    },
    {
      id: "user-15",
      name: "Pengguna 15",
      role: "USER",
      points: 569,
      rank: 8,
    },
    {
      id: "user-4",
      name: "Pengguna 4",
      role: "USER",
      points: 519,
      rank: 9,
    },
    {
      id: "user-8",
      name: "Pengguna 8",
      role: "USER",
      points: 515,
      rank: 10,
    },
    {
      id: "user-11",
      name: "Pengguna 11",
      role: "USER",
      points: 490,
      rank: 11,
    },
    {
      id: "user-12",
      name: "Pengguna 12",
      role: "USER",
      points: 480,
      rank: 12,
    },
    {
      id: "user-10",
      name: "Pengguna 10",
      role: "USER",
      points: 405,
      rank: 13,
    },
    {
      id: "user-5",
      name: "Pengguna 5",
      role: "USER",
      points: 397,
      rank: 14,
    },
    {
      id: "user-14",
      name: "Pengguna 14",
      role: "USER",
      points: 361,
      rank: 15,
    },
    {
      id: "user-3",
      name: "Pengguna 3",
      role: "USER",
      points: 356,
      rank: 16,
    },
    {
      id: "user-6",
      name: "Pengguna 6",
      role: "USER",
      points: 262,
      rank: 17,
    },
    {
      id: "user-16",
      name: "Pengguna 16",
      role: "USER",
      points: 258,
      rank: 18,
    },
    {
      id: "user-19",
      name: "Pengguna 19",
      role: "USER",
      points: 122,
      rank: 19,
    },
    {
      id: "user-17",
      name: "Pengguna 17",
      role: "USER",
      points: 56,
      rank: 20,
    },
  ],
  myRank: 15,
  myPoints: 361,
  role: "USER",
  page: 1,
};

export const MOCK_ADMIN_DASHBOARD_DATA: AdminAnalyticData = {
  totalUser: 150,
  totalPetugas: 10,
  totalTransaksi: 65,
  totalSampah: [
    { type: "PLASTIC", total: 120 },
    { type: "PAPER", total: 90 },
    { type: "METAL", total: 30 },
    { type: "ORGANIC", total: 50 },
    { type: "OTHER", total: 80 },
  ],
  transaksiPerBulan: [
    { bulan: 8, tahun: 2024, jumlah: 120 },
    { bulan: 9, tahun: 2024, jumlah: 140 },
    { bulan: 10, tahun: 2024, jumlah: 135 },
    { bulan: 11, tahun: 2024, jumlah: 160 },
    { bulan: 12, tahun: 2024, jumlah: 180 },
    { bulan: 1, tahun: 2025, jumlah: 200 },
    { bulan: 2, tahun: 2025, jumlah: 190 },
    { bulan: 3, tahun: 2025, jumlah: 220 },
    { bulan: 4, tahun: 2025, jumlah: 250 },
    { bulan: 5, tahun: 2025, jumlah: 270 },
    { bulan: 6, tahun: 2025, jumlah: 260 },
    { bulan: 7, tahun: 2025, jumlah: 300 },
    { bulan: 8, tahun: 2025, jumlah: 290 },
    { bulan: 9, tahun: 2025, jumlah: 420 },
    { bulan: 10, tahun: 2025, jumlah: 320 },
    { bulan: 11, tahun: 2025, jumlah: 390 },
  ],
  transaksiStatus: {
    pending: 15,
    approved: 42,
    rejected: 8,
  },
};
